### ISSUE TITLE
Checkmate error(?)

### ISSUE THREAD

**Issue by AndresDKoombea** [marcinguy/betterscan-ce#97]
Hi there

I was using the cli-html option in a few repositories and it was working without issues, then last night the scan started to show this error:

_Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/checkmate-0.2.0-py3.8.egg/checkmate/lib/code/environment.py", line 561, in analyze_file_revision
    analyzer_results = analyzer.analyze(file_revision)
  File "/usr/local/lib/python3.8/site-packages/checkmate-0.2.0-py3.8.egg/checkmate/contrib/plugins/all/fluidattacksscanner/analyzer.py", line 72, in analyze
    next(reader)
StopIteration_

And now I'm stucked, if I try to run the scan again it says that it's already created and abort but I don't have the HTML report 

Thanks in advance

**Comment by marcinguy** [comment]
@AndresDKoombea Try to prune the images and get the latest one. Let me know how it goes

**Comment by AndresDKoombea** [comment]
Thank you so much, that did the trick
